services:
  api:
    build:
      dockerfile: Dockerfile
    container_name: shorten_api
    env_file:
      - ".env"
    ports:
      - "8000:8000"
    networks:
      - shorten-api_shared
    depends_on:
      - db
      - cache

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - ".env"
    environment:
      POSTGRES_DB: ${PG_DATABASE_NAME}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shorten-api_shared

  cache:
    container_name: redis_cache
    image: redis
    ports: 
      - "6379:6379"
    volumes:
      - ./tools/docker/redis_data:/data
    command: "redis-server /data/redis.conf"
    env_file:
      - ".env"
    networks:
      - shorten-api_shared

networks:
  shorten-api_shared:
    external: true

volumes:
  postgres_data:
  redis_data: